apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
spec:
  clusterName: e2e-monitor
  git:
    syncRepo: https://github.com/elastic/cloud-on-k8s-infra
    policyDir: "policy"
    secretType: none
    syncWait: 60