apiVersion: v1
kind: ConfigMap
metadata:
  name: snapshot-policy
data:
  snapshot-policy.json: |
    {
      "name": "weekly-snap-{now}",
      "schedule": "0 0 0 ? * 1",
      "repository": "gcs-snapshot-repo",
      "config": {}
    }
